name: Deploy to GitHub Pages

on:
  # Re-deploy every push to the default branch
  push:
    branches: [master, main]
  # Allow manual runs from the Actions tab
  workflow_dispatch:

permissions:
  contents: read         # to checkout the repo
  pages: write           # to deploy to Pages
  id-token: write        # to verify the deployment originates from the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build
        env:
          NODE_ENV: production

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Upload the static files as an artifact so deploy-pages can access them
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 